ALTER TABLE tenants ADD COLUMN short_name VARCHAR(100);
ALTER TABLE tenants ADD COLUMN school_type VARCHAR(64);
ALTER TABLE tenants ADD COLUMN province VARCHAR(64);
ALTER TABLE tenants ADD COLUMN city VARCHAR(64);
ALTER TABLE tenants ADD COLUMN website VARCHAR(255);
ALTER TABLE tenants ADD COLUMN contact_phone VARCHAR(32);
ALTER TABLE tenants ADD COLUMN scale_data JSON DEFAULT (JSON_OBJECT());
ALTER TABLE tenants ADD COLUMN secondary_colleges JSON DEFAULT (JSON_ARRAY());
