import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true, channel: 'chrome', args: ['--no-sandbox'] })
const page = await browser.newPage()
page.on('console', m => { if (m.type() === 'error') console.log('[console]', m.text().slice(0, 100)) })
page.on('response', r => { if (r.url().includes('/api/')) console.log('[resp]', r.status(), r.request().method(), r.url().replace('http://127.0.0.1','')) })
page.on('pageerror', e => console.log('[pageerror]', e.message.slice(0, 100)))
await page.goto('http://127.0.0.1/portal/login', { waitUntil: 'domcontentloaded', timeout: 30000 })
console.log('page loaded, url:', page.url())
await page.waitForTimeout(2000)
await page.fill('#username', 'school')
await page.fill('#password', 'school123')
await page.click('button[type="submit"]')
await page.waitForTimeout(6000)
console.log('[after login] url:', page.url())
await browser.close()
