ALTER TABLE tenants ADD COLUMN IF NOT EXISTS short_name VARCHAR(100);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS school_type VARCHAR(64);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS province VARCHAR(64);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS city VARCHAR(64);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(32);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS scale_data JSONB DEFAULT '{}';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS secondary_colleges JSONB DEFAULT '[]';
