// ============================================================
// 【演示数据】混合课程初始课程树占位 mock（Web 前端开发示例）
// 引用方：lesson/admin/hybrid/add/page.tsx 作为新建混合课程的初始课程树
// 后续规划：改为空初始树或由后端课程模板接口提供后删除本文件
// ============================================================
import type { SystemCourseNode } from '@/lib/types/lesson-source'

export const WEB_FRONTEND_SEMESTER_NODES: SystemCourseNode[] = [
  {
    id: 'hybrid-node-1',
    courseId: 'hybrid-1',
    parentId: null,
    name: 'Web前端开发混合课程',
    order: 1,
    type: 'normal',
    status: 'published',
    teachingGoals: '掌握Web前端开发的核心知识与工程实践能力',
    duration: 64,
  },
  {
    id: 'node-w1',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第1周：课程导论与开发环境',
    order: 1,
    type: 'normal',
    status: 'published',
    teachingGoals: '了解课程目标、考核方式，搭建前端开发环境',
    duration: 4,
  },
  {
    id: 'node-w2',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第2周：HTML 基础与语义化',
    order: 2,
    type: 'normal',
    status: 'published',
    teachingGoals: '掌握 HTML 标签、文档结构与语义化编写规范',
    duration: 4,
  },
  {
    id: 'node-w3',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第3周：HTML5 新特性',
    order: 3,
    type: 'normal',
    status: 'published',
    teachingGoals: '理解 HTML5 表单、多媒体、Canvas 等新增特性',
    duration: 4,
  },
  {
    id: 'node-w4',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第4周：CSS 选择器与文本样式',
    order: 4,
    type: 'normal',
    status: 'published',
    teachingGoals: '掌握 CSS 选择器优先级、字体、颜色、盒模型基础',
    duration: 4,
  },
  {
    id: 'node-w5',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第5周：CSS 盒模型与定位',
    order: 5,
    type: 'normal',
    status: 'published',
    teachingGoals: '深入理解盒模型、浮动、定位与层叠上下文',
    duration: 4,
  },
  {
    id: 'node-w6',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第6周：Flexbox 弹性布局',
    order: 6,
    type: 'normal',
    status: 'published',
    teachingGoals: '熟练使用 Flexbox 完成常见页面布局',
    duration: 4,
  },
  {
    id: 'node-w7',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第7周：Grid 网格布局',
    order: 7,
    type: 'normal',
    status: 'published',
    teachingGoals: '掌握 CSS Grid 网格布局的核心概念与应用',
    duration: 4,
  },
  {
    id: 'node-w8',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第8周：响应式页面设计',
    order: 8,
    type: 'normal',
    status: 'published',
    teachingGoals: '理解媒体查询、移动优先与响应式适配策略',
    duration: 4,
  },
  {
    id: 'node-w9',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第9周：期中项目实践（企业官网）',
    order: 9,
    type: 'original',
    status: 'published',
    teachingGoals: '综合运用 HTML/CSS 完成企业官网静态页面',
    duration: 4,
  },
  {
    id: 'node-w10',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第10周：JavaScript 基础语法',
    order: 10,
    type: 'normal',
    status: 'published',
    teachingGoals: '掌握变量、数据类型、运算符、流程控制与函数',
    duration: 4,
  },
  {
    id: 'node-w11',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第11周：DOM 操作与事件处理',
    order: 11,
    type: 'normal',
    status: 'published',
    teachingGoals: '熟练使用 DOM API 与常见事件模型',
    duration: 4,
  },
  {
    id: 'node-w12',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第12周：表单验证与正则表达式',
    order: 12,
    type: 'normal',
    status: 'published',
    teachingGoals: '完成客户端表单验证与正则表达式应用',
    duration: 4,
  },
  {
    id: 'node-w13',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第13周：前端组件化开发',
    order: 13,
    type: 'normal',
    status: 'published',
    teachingGoals: '理解组件化思想，掌握组件封装与复用方法',
    duration: 4,
  },
  {
    id: 'node-w14',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第14周：Vue 基础与指令',
    order: 14,
    type: 'normal',
    status: 'published',
    teachingGoals: '掌握 Vue 3 基础语法、指令与响应式数据',
    duration: 4,
  },
  {
    id: 'node-w15',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第15周：Vue 组件与路由',
    order: 15,
    type: 'normal',
    status: 'published',
    teachingGoals: '掌握 Vue 组件通信与 Vue Router 基础应用',
    duration: 4,
  },
  {
    id: 'node-w16',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第16周：综合项目实战（电商后台）',
    order: 16,
    type: 'original',
    status: 'published',
    teachingGoals: '综合运用前端技术栈完成电商后台管理系统',
    duration: 4,
  },
  {
    id: 'node-w17',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第17周：性能优化与工程化',
    order: 17,
    type: 'normal',
    status: 'published',
    teachingGoals: '了解前端性能优化、构建工具与代码规范',
    duration: 4,
  },
  {
    id: 'node-w18',
    courseId: 'hybrid-1',
    parentId: 'hybrid-node-1',
    name: '第18周：期末复习与考核',
    order: 18,
    type: 'normal',
    status: 'published',
    teachingGoals: '回顾全学期知识要点，完成期末项目答辩',
    duration: 4,
  },
]
